In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [103]:
df=pd.read_csv(r'C:\Users\acer\Desktop\數據分析與機器學習\期末報告\train_data.csv')

In [127]:
df

name  rate          subject  income_per_month buy_tablet_or_not  \
0      Olivia    12               CS             45890                 y   
1       Ethan     5               CS             51235                 y   
2         Ava    17   EE(Electronic)             36741                 n   
3       Mason     3               ME             40219                 n   
4    Isabella     8               ME             54380                 y   
5        Liam     6               CS             39874                 n   
6      Sophia    14  EE(Electrical )             57302                 y   
7     Jackson    10               ME             32987                 n   
8        Emma    20   EE(Electronic)             47250                 n   
9       Aiden     2  EE(Electrical )             54106                 y   
10        Mia     1               CS             30562                 n   
11      Lucas    18               ME             57643                 y   
12     Harper     7               CS             48795                 n   
13       Noah    11               ME             35321                 n   
14    Abigail    13  EE(Electrical )             41908                 n   
15       Ella    15   EE(Electronic)             53674                 y   
16  Alexander    16               ME             38899                 y   
17      Grace    19  EE(Electrical )             45213                 y   
18     Elijah     4   EE(Electronic)             51247                 y   
19   Scarlett     9               CS             34125                 y   

    Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  \
0          NaN         NaN         NaN         NaN         NaN          NaN   
1          NaN         NaN         NaN         NaN         NaN          NaN   
2          NaN         NaN         NaN         NaN         NaN          NaN   
3          NaN         NaN         NaN         NaN         NaN          NaN   
4          NaN         NaN         NaN         NaN         NaN          NaN   
5          NaN         NaN         NaN         NaN         NaN          NaN   
6          NaN         NaN         NaN         NaN         NaN          NaN   
7          NaN         NaN         NaN         NaN         NaN          NaN   
8          NaN         NaN         NaN         NaN         NaN          NaN   
9          NaN         NaN         NaN         NaN         NaN          NaN   
10         NaN         NaN         NaN         NaN         NaN          NaN   
11         NaN         NaN         NaN         NaN         NaN          NaN   
12         NaN         NaN         NaN         NaN         NaN          NaN   
13         NaN         NaN         NaN         NaN         NaN          NaN   
14         NaN         NaN         NaN         NaN         NaN          NaN   
15         NaN         NaN         NaN         NaN         NaN          NaN   
16         NaN         NaN         NaN         NaN         NaN          NaN   
17         NaN         NaN         NaN         NaN         NaN          NaN   
18         NaN         NaN         NaN         NaN         NaN          NaN   
19         NaN         NaN         NaN         NaN         NaN          NaN   

    Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  \
0           NaN          NaN          NaN          NaN          NaN   
1           NaN          NaN          NaN          NaN          NaN   
2           NaN          NaN          NaN          NaN          NaN   
3           NaN          NaN          NaN          NaN          NaN   
4           NaN          NaN          NaN          NaN          NaN   
5           NaN          NaN          NaN          NaN          NaN   
6           NaN          NaN          NaN          NaN          NaN   
7           NaN          NaN          NaN          NaN          NaN   
8           NaN          NaN          NaN          NaN          NaN   
9           NaN          NaN          NaN 

In [104]:
df.columns

Index(['name', 'rate', 'subject', 'income_per_month', 'buy_tablet_or_not',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18'],
      dtype='object')

In [105]:
# 欄位設定
x_col = ['name', 'rate', 'subject', 'income_per_month', 'buy_tablet_or_not']

x_num_col = ['rate','income_per_month']
x_cat_col = ['subject']

In [106]:
df_cat = df[x_cat_col]
df_num = df[x_num_col]

處理數值型

In [107]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import make_pipeline
num_pl=make_pipeline(MinMaxScaler())
numcol_input=num_pl.fit_transform(df_num)
numcol_input

array([[0.57894737, 0.56600569],
       [0.21052632, 0.76337654],
       [0.84210526, 0.22816735],
       [0.10526316, 0.35659688],
       [0.36842105, 0.87950962],
       [0.26315789, 0.34385732],
       [0.68421053, 0.98740815],
       [0.47368421, 0.08954618],
       [1.        , 0.6162254 ],
       [0.05263158, 0.86939182],
       [0.        , 0.        ],
       [0.89473684, 1.        ],
       [0.31578947, 0.67327647],
       [0.52631579, 0.17573206],
       [0.63157895, 0.41896533],
       [0.73684211, 0.85343968],
       [0.78947368, 0.30785422],
       [0.94736842, 0.54100661],
       [0.15789474, 0.76381965],
       [0.42105263, 0.13156826]])

In [108]:
pd.DataFrame(numcol_input.round(3),columns=x_num_col)

rate  income_per_month
0   0.579             0.566
1   0.211             0.763
2   0.842             0.228
3   0.105             0.357
4   0.368             0.880
5   0.263             0.344
6   0.684             0.987
7   0.474             0.090
8   1.000             0.616
9   0.053             0.869
10  0.000             0.000
11  0.895             1.000
12  0.316             0.673
13  0.526             0.176
14  0.632             0.419
15  0.737             0.853
16  0.789             0.308
17  0.947             0.541
18  0.158             0.764
19  0.421             0.132

處理類別型

In [109]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder()
cat_pl=make_pipeline(OneHotEncoder(sparse=False))
catcol_input=cat_pl.fit_transform(df_cat)
catcol_input

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [110]:
cat_colname=cat_pl.named_steps['onehotencoder'].get_feature_names_out(x_cat_col)
cat_colname=list(cat_colname)

In [116]:
pd.DataFrame(catcol_input.round(3),columns=cat_colname)

subject_CS  subject_EE(Electrical )  subject_EE(Electronic)  subject_ME
0          1.0                      0.0                     0.0         0.0
1          1.0                      0.0                     0.0         0.0
2          0.0                      0.0                     1.0         0.0
3          0.0                      0.0                     0.0         1.0
4          0.0                      0.0                     0.0         1.0
5          1.0                      0.0                     0.0         0.0
6          0.0                      1.0                     0.0         0.0
7          0.0                      0.0                     0.0         1.0
8          0.0                      0.0                     1.0         0.0
9          0.0                      1.0                     0.0         0.0
10         1.0                      0.0                     0.0         0.0
11         0.0                      0.0                     0.0         1.0
12         1.0                      0.0                     0.0         0.0
13         0.0                      0.0                     0.0         1.0
14         0.0                      1.0                     0.0         0.0
15         0.0                      0.0                     1.0         0.0
16         0.0                      0.0                     0.0         1.0
17         0.0                      1.0                     0.0         0.0
18         0.0                      0.0                     1.0         0.0
19         1.0                      0.0                     0.0         0.0

In [111]:
num_input=np.array(numcol_input)
cat_input=np.array(catcol_input)

#name=np.array(df['name'])
input_data=np.hstack((num_input,cat_input))

pd.DataFrame(input_data,columns=x_num_col+cat_colname)

rate  income_per_month  subject_CS  subject_EE(Electrical )  \
0   0.578947          0.566006         1.0                      0.0   
1   0.210526          0.763377         1.0                      0.0   
2   0.842105          0.228167         0.0                      0.0   
3   0.105263          0.356597         0.0                      0.0   
4   0.368421          0.879510         0.0                      0.0   
5   0.263158          0.343857         1.0                      0.0   
6   0.684211          0.987408         0.0                      1.0   
7   0.473684          0.089546         0.0                      0.0   
8   1.000000          0.616225         0.0                      0.0   
9   0.052632          0.869392         0.0                      1.0   
10  0.000000          0.000000         1.0                      0.0   
11  0.894737          1.000000         0.0                      0.0   
12  0.315789          0.673276         1.0                      0.0   
13  0.526316          0.175732         0.0                      0.0   
14  0.631579          0.418965         0.0                      1.0   
15  0.736842          0.853440         0.0                      0.0   
16  0.789474          0.307854         0.0                      0.0   
17  0.947368          0.541007         0.0                      1.0   
18  0.157895          0.763820         0.0                      0.0   
19  0.421053          0.131568         1.0                      0.0   

    subject_EE(Electronic)  subject_ME  
0                      0.0         0.0  
1                      0.0         0.0  
2                      1.0         0.0  
3                      0.0         1.0  
4                      0.0         1.0  
5                      0.0         0.0  
6                      0.0         0.0  
7                      0.0         1.0  
8                      1.0         0.0  
9                      0.0         0.0  
10                     0.0         0.0  
11                     0.0         1.0  
12                     0.0         0.0  
13                     0.0         1.0  
14                     0.0         0.0  
15                     1.0         0.0  
16                     0.0         1.0  
17                     0.0         0.0  
18                     1.0         0.0  
19                     0.0         0.0

In [112]:
train_x = input_data[:14]
train_y = df['buy_tablet_or_not'][0:14]
    
test_x = input_data[14:]
test_y = df['buy_tablet_or_not'][14:]

In [113]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier(criterion='entropy',random_state=0)
tree.fit(train_x,train_y)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [117]:
tree.predict(test_x)

array(['n', 'y', 'n', 'y', 'y', 'n'], dtype=object)

In [118]:
tree.score(test_x,test_y).round(3)

0.667

In [115]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,tree.predict(test_x))

array([[1, 0],
       [2, 3]], dtype=int64)

In [120]:
output=tree.predict(test_x)

array(['n', 'y', 'n', 'y', 'y', 'n'], dtype=object)

In [195]:
wili_buy=[]
for i in range(len(output)):
    if output[i]=='y':
        wili_buy.append(df['name'][i+14])
wili_buy

['Ella', 'Grace', 'Elijah']

In [176]:
import pymysql

db_settings = {
  "host" : "127.0.0.1",
  "port" : 3306,
  "user" : "root" ,
  "password" : "0000" ,
  "db" : "db_for_tablet" ,# 根據你的資料庫名稱
  "charset" : "utf8"
}

In [201]:
results=()
try:
    # 建立Connection物件
    conn = pymysql.connect(**db_settings)
    print("連線成功")

    with conn.cursor() as cursor: 
        cursor.execute("select * from `student`")
        
        # 獲取所有查詢結果
        results = cursor.fetchall()    
        #with statement 完成後，會自動關閉資料庫的連線操作，詳請需要 with 指令

except Exception as ex: # 出現意外時印出
    print("出現例外情況")
    print(ex)
results

連線成功


(('C0015', 'Abigail', '0912345678', 'A_UNIVERSITY'),
 ('C0017', 'Alexander', '0934567890', 'C_UNIVERSITY'),
 ('C0020', 'Scarlett', '0967890123', 'C_UNIVERSITY'),
 ('C0018', 'Grace', '0945678901', 'B_UNIVERSITY'),
 ('C0019', 'Elijah', '0956789012', 'A_UNIVERSITY'),
 ('C0016', 'Ella', '0923456789', 'B_UNIVERSITY'))

將資料庫中的資料與測試結果為會購買的客人做比對

In [207]:
data_insert=[]

for i in range(len(wili_buy)):
    for j in range(len(results)):
        if wili_buy[i]==results[j][1]:
            data_insert.append(results[j])
    
data_insert

[('C0016', 'Ella', '0923456789', 'B_UNIVERSITY'),
 ('C0018', 'Grace', '0945678901', 'B_UNIVERSITY'),
 ('C0019', 'Elijah', '0956789012', 'A_UNIVERSITY')]

In [208]:
try:
    # 建立Connection物件
    conn = pymysql.connect(**db_settings)
    print("連線成功")
    
    with conn.cursor() as cursor:
        for i in range(len(data_insert)): 
            cursor.execute("insert into `customer_list` (\
            `customer_ID`,\
            `customer_name`,\
            `phone`,\
            `school` ) values (%s,%s,%s,%s)",\
            (data_insert[i]))
        
        conn.commit()
        #with statement 完成後，會自動關閉資料庫的連線操作，詳請需要 with 指令
    print("資料新增成功")
except Exception as ex: # 出現意外時印出
    print("出現例外情況")
    print(ex)

連線成功
資料新增成功


In [209]:
results=[]
try:
    # 建立Connection物件
    conn = pymysql.connect(**db_settings)
    print("連線成功")

    with conn.cursor() as cursor: 
        cursor.execute("select * from `customer_list`")
        
        # 獲取所有查詢結果
        results = cursor.fetchall()    
        #with statement 完成後，會自動關閉資料庫的連線操作，詳請需要 with 指令

except Exception as ex: # 出現意外時印出
    print("出現例外情況")
    print(ex)

results

連線成功


(('C0016', 'Ella', '0923456789', 'B_UNIVERSITY'),
 ('C0018', 'Grace', '0945678901', 'B_UNIVERSITY'),
 ('C0019', 'Elijah', '0956789012', 'A_UNIVERSITY'))